[package]
name = "ground-station"
version = "0.0.0"
edition = "2021"

[dependencies]
eframe = { version = "0.15", default-features = false, features = [
    "default_fonts",
    "egui_glow",
] }
wmidi = "4.0"
