[package]
name = "ground-station"
version = "0.0.0"
edition = "2021"

[dependencies]
iced = { version = "0.3", features = ["async-std", "canvas"] }
async-std = "1.10"
plotters = "0.3"
plotters-iced = "0.1"
wmidi = "4.0"
